<template>

    <div class="px-4 pb-4">
        <div class="flex justify-end mt-4 space-x-3">
            <div class="bg-primary text-white py-1 px-2 mr-2 rounded-lg cursor-pointer"> 
                back
            </div>
        </div>
    
        <div> 
            <div class="font-bold"> 
                My Collection
            </div>
            <div class="mt-4 flex w-full justify-between"> 
                <div class="border rounded-lg p-2" style="width: 40%"> 
                    <div class="flex my-2 space-x-4"> 
                        <div class="font-bold text-2xl">Name</div>
                        <div class="font-bold text-2xl">SYM</div>
                    </div>
                    <div class="flex flex-col"> 
                        
                        <div class="border p-2 flex items-center justify-center h-64"> 
                            image
                        </div>
                        <div class="mt-2"> 
                            
                            Bored Ape Yacht Club, often colloquially called Bored Apes, Bored Ape or BAYC, is a non-fungible token collection built on the Ethereum blockchain with the ERC-721 standard. The collection features profile pictures of cartoon apes that are procedurally generated by an algorithm.
                        </div>
                    </div>
                </div>

                <div style="width: 50%"> 
                    <div class="font-bold">My Items</div>
                    <simple-table :columns="columns" :table-data="tableData" :has-search="false">
                        <template v-slot:actions="{itemData}">
                          <div class="">
                            <div class="flex items-center">
                                <span class="flex items-center mr-3 text-primary2 hover:font-bold cursor-pointer" @click="viewProduct(itemData)">
                                <svg-icon name="view" height="h-5" width="w-5" class="mr-1" color="#257ae4"></svg-icon>
                                  view 
                              </span>
                            </div>
                          </div>
                        </template>
                    </simple-table>
                </div>
            </div>
        </div>
    </div>
</template>
 

<script setup>
import NavBar from '@/components/NavBar.vue';
import { ref } from 'vue';
import SimpleTable from "@/components/shared/SimpleTable.vue";
import { useRouter } from 'vue-router';

const router = useRouter()

const qty = ref(1);
const viewProduct = (item) => {
  console.log(item.tokenId)
  router.push(`/item/${item.tokenId}`)
}
const columns = ref({
    "itemName": "Item Name",
    "quantity": "Supply",
    "price": "Price",
})
const tableData = ref([
    {
        "itemName": "Sady luki tshirts",
        "unitPrice": "12000 Atsh",
        "quantity": 2,
        "price": 120000,
        "tokenId": 1
    },
    {
        "itemName": "Sady luki tshirts",
        "unitPrice": "12000 Atsh",
        "quantity": 2,
        "price": 120000,
        "tokenId": 1
    },
    {
        "itemName": "Sady luki tshirts",
        "unitPrice": "12000 Atsh",
        "quantity": 2,
        "price": 120000,
        "tokenId": 1
    },
    {
        "itemName": "Sady luki tshirts",
        "unitPrice": "12000 Atsh",
        "quantity": 2,
        "price": 120000,
        "tokenId": 1
    },
    {
        "itemName": "Sady luki tshirts",
        "unitPrice": "12000 Atsh",
        "quantity": 2,
        "price": 120000,
        "tokenId": 1
    },
    {
        "itemName": "Sady luki tshirts",
        "unitPrice": "12000 Atsh",
        "quantity": 2,
        "price": 120000,
        "tokenId": 1
    },
])

</script>
 