<template>
    <div class="px-4 pb-4">{{ tableData }}

        <add-edit-sponsor-testimonials :open-dialog="addEditTestimonials"  @close-dialog="addEditTestimonials = false;"></add-edit-sponsor-testimonials>

        <div class="flex justify-end mt-4 space-x-3">
            <div @click="goBack" class="bg-primary2 text-white py-1 px-2 mr-2 rounded-lg cursor-pointer"> 
                Mint Item
            </div>
            <div @click="goBack" class="bg-primary text-white py-1 px-2 mr-2 rounded-lg cursor-pointer"> 
                Back
            </div>
        </div>
    
        <div> 
            <div class="font-bold"> 
                My Collection
            </div>
            <div class="mt-4 flex w-full justify-between"> 
                <div class="border rounded-lg p-2" style="width: 40%"> 
                    <div class="flex my-2 space-x-4"> 
                        <div class="font-bold text-2xl">Name</div>
                        <div class="font-bold text-2xl">SYM</div>
                    </div>
                    <div class="flex flex-col"> 
                        
                        <div class="border p-2 flex items-center justify-center h-64"> 
                            <img src="http://127.0.0.1:8080/ipfs/QmWRGap3aeEm6fjudmq99qNrsAeBTbf4mF8AJ7YutWiZdY" alt="icon description" class="p-2 h-64">
                        </div>
                        <div class="mt-4"> 
                            
                            Bored Ape Yacht Club, often colloquially called Bored Apes, Bored Ape or BAYC, is a non-fungible token collection built on the Ethereum blockchain with the ERC-721 standard. The collection features profile pictures of cartoon apes that are procedurally generated by an algorithm.
                        </div>
                    </div>
                </div>

                <div style="width: 50%"> 
                    <div class="font-bold">My Items</div>
                    <simple-table :columns="columns" :table-data="tokens" :has-search="false">
                        <template v-slot:actions="{itemData}">
                          <div class="">
                            <div class="flex items-center">
                                <span class="flex items-center mr-3 text-primary2 hover:font-bold cursor-pointer" @click="viewProduct(itemData)">
                                <svg-icon name="view" height="h-5" width="w-5" class="mr-1" color="#257ae4"></svg-icon>
                                  view 
                              </span>
                            </div>
                          </div>
                        </template>
                    </simple-table>
                </div>
            </div>
        </div>
    </div>
</template>
 

<script setup>
import NavBar from '@/components/NavBar.vue';
import { computed, onMounted, ref } from 'vue';
import SimpleTable from "@/components/shared/SimpleTable.vue";
import { useRouter } from 'vue-router';
import {getSignerContract} from '../../scripts/ContractUtils';
import {ipfsGateway, nftMyCollection_ABI} from "../../scripts/ContractConstants";
import {ethers} from 'ethers';


let {nftFactory_contract, signer} = getSignerContract();
const nftMyCollection_Address = ref("0x6487069Fc424124c46F1aaEA64344CDA2eC78A00");

const nftMyCollection_contract = new ethers.Contract(nftMyCollection_Address.value, nftMyCollection_ABI, signer);

const router = useRouter()

const tokens = ref([])
const tokensData = ref([])


const tableData = computed(() => {
    return tokens.value.map((tokenIndex) => {
        return {
            url: `http://127.0.0.1:8080/ipfs/${tokenIndex}`
        };
    });
});

const fetchData = async () => {
    const responseData = []; // Array to store response data
    for (const item of tableData.value) {
        try {
            const response = await fetch(item.url);
            const data = await response.json();
            responseData.push(data); // Push data to responseData array
            console.log('Data for', item.url, ':', data);
            // Handle data as needed
        } catch (error) {
            console.error('Error fetching data from', item.url, ':', error);
            // Handle error
        }
    }
    return responseData; // Return the array of response data
};



const qty = ref(1);
const viewProduct = (item) => {
  console.log(item.tokenId)
  router.push(`/item/${item.tokenId}`)
}

const myNft = ref()
const logoCID = ref()

onMounted(async () => {
    // Get details of the nft
    // myNft.value = nftFactory_contract.getNFTCollectionByAddress(
    //     "0xf6780ab367a1E61a0c3a84EdccD270bF5Fcb6606"
    // )

    // Get all tokens in this collection
    tokens.value  = await nftMyCollection_contract.getAllCollectionTokens();
    

    console.log(tokens.value );
    tokensData.value = fetchData().then((responseData) => {
    console.log('All response data:', responseData);
    // Further processing of responseData
});
    

})

const columns = ref({
    "image": " ",
    "itemName": "Item Name",
    "description": "Description",
})

</script>
 